name: "Cloudflare Purge Zone Cache"
description: "Clear or Purge the cache of a zone or multiple domains on Cloudflare."
author: "Shane"
branding:
  icon: "cloud"
  color: "orange"

inputs:
  token:
    description: "Cloudflare API Token"
    required: true
  domains:
    description: "Cloudflare Domains to Purge"
    required: false
    default: ""
  zone:
    description: "For Backwards Compatibility ONLY"
    required: false

runs:
  using: "docker"
  image: "docker://ghcr.io/cssnr/cloudflare-purge-cache-action:v1"
