name: "Cloudflare Purge Zone Cache"
description: "Clear or Purge the cache of Cloudflare zones with optional filters."
author: "Shane"
branding:
  icon: "cloud"
  color: "orange"

inputs:
  token:
    description: "Cloudflare API Token"
    required: true
  zones:
    description: "Zones to Purge"
    required: false
    default: ""
  files:
    description: "Files to Purge"
    required: false
    default: ""
  prefix:
    description: "File Prefix"
    required: false
    default: ""
  tags:
    description: "Tags to Purge"
    required: false
    default: ""
  hosts:
    description: "Hosts to Purge"
    required: false
    default: ""
  prefixes:
    description: "Prefixes to Purge"
    required: false
    default: ""
  fail:
    description: "Fail Mode"
    required: false
    default: "all"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  dry_run:
    description: "Run Without Purging Cache"
    required: false
    default: "false"
  zone:
    description: "This has been replaced by: zones"
    deprecationMessage: "Please update this input to: zones"
    required: false
  domains:
    description: "This has been replaced by: zones"
    deprecationMessage: "Please update this input to: zones"
    required: false

outputs:
  success:
    description: "Successful Zones"
  failed:
    description: "Failed Zones"

runs:
  using: "docker"
  image: "docker://ghcr.io/cssnr/cloudflare-purge-cache-action:v2.0.2"
