name: "Test"

on:
  workflow_dispatch:
  schedule:
    - cron: "18 18 * * 1,3,5"
  push:

env:
  DOMAINS: cssnr.com,example.com

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Edit YAML"
        uses: Liam-Johnston/yaml-helper@V1
        if: ${{ !github.event.act }}
        with:
          file-location: "action.yml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: src/Dockerfile

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          zone: ${{ env.DOMAINS }} # DO NOT USE 'zone'! Use 'domains' instead!
          dry_run: true

      - name: "Verify Outputs"
        if: ${{ env.DOMAINS == 'cssnr.com,example.com' }}
        run: |
          echo "success: '${{ steps.test.outputs.success }}'"
          if [ "${{ steps.test.outputs.success }}" != "cssnr.com" ];then
            echo "Output Verification Failed: success"
            exit 1
          fi
          echo "failed: '${{ steps.test.outputs.failed }}'"
          if [ "${{ steps.test.outputs.failed }}" != "example.com" ];then
            echo "Output Verification Failed: failed"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ always() && failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
