name: "Test"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

env:
  DOMAINS: cssnr.com,example.com

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Edit YAML"
        uses: Liam-Johnston/yaml-helper@V1
        if: ${{ !github.event.act }}
        with:
          file-location: "action.yml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: src/Dockerfile

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domains: ${{ env.DOMAINS }}
          dry_run: true

      - name: "Validate Outputs"
        run: |
          echo "success: '${{ steps.test.outputs.success }}'"
          if [ "${{ steps.test.outputs.success }}" != "cssnr.com" ];then
            echo "Output Verification Failed: success"
            exit 1
          fi
          echo "failed: '${{ steps.test.outputs.failed }}'"
          if [ "${{ steps.test.outputs.failed }}" != "example.com" ];then
            echo "Output Verification Failed: failed"
            exit 1
          fi

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python 3.11"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Flake8"
        run: |
          python -m pip install flake8
          flake8 src

      - name: "Black"
        uses: psf/black@stable
