name: "Test"

on:
  workflow_dispatch:
  schedule:
    - cron: "18 18 * * 1,3,5"
  push:
    branches: ["**"]
    paths:
      - "dist/**"
      - "src/**"
      - ".github/workflows/test.yaml"
      - "package*.json"
      - "requirements*.txt"
      - "action.yaml"

env:
  ZONES: ${{ vars.ZONES || 'cssnr.com,example.com' }}
  FILES: ""
  PREFIX: ""
  TAGS: ""
  HOSTS: ""
  PREFIXES: ""
  DRY_RUN: "true"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Edit YAML"
        uses: Liam-Johnston/yaml-helper@V1
        if: ${{ !github.event.act }}
        with:
          file-location: "action.yaml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: Dockerfile

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          domains: ${{ env.ZONES }} # DO NOT USE 'domains' use 'zones' instead...
          dry_run: ${{ env.DRY_RUN }}
          files: ${{ env.FILES }}
          prefix: ${{ env.PREFIX }}
          tags: ${{ env.TAGS }}
          hosts: ${{ env.HOSTS }}
          prefixes: ${{ env.PREFIXES }}

      - name: "Verify Outputs"
        if: ${{ env.ZONES == 'cssnr.com,example.com' }}
        run: |
          echo "success: '${{ steps.test.outputs.success }}'"
          if [ "${{ steps.test.outputs.success }}" != "cssnr.com" ];then
            echo "Output Verification Failed: success"
            exit 1
          fi
          echo "failed: '${{ steps.test.outputs.failed }}'"
          if [ "${{ steps.test.outputs.failed }}" != "example.com" ];then
            echo "Output Verification Failed: failed"
            exit 1
          fi

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
